// Web versions of the originals in src/images/, generated by scripts/build-images.mjs.
import manifest from '../generated/images.json';

export interface WebImage {
	/** At most 2000px on the long side. */
	src: string;
	width: number;
	height: number;
	/** 800px wide. */
	thumb: string;
	thumbWidth: number;
	thumbHeight: number;
	/** 1200x630 JPEG for link previews. */
	share: string;
}

const images: Record<string, WebImage> = manifest.images;

/** Web versions of one original, by its path under src/images/, e.g. "home/IMG_3853.JPG". */
export function image(path: string): WebImage {
	const found = images[path];
	if (!found) throw new Error(`No image src/images/${path} (or run \`npm run images\` to generate it).`);
	return found;
}

/** Web versions of every original directly inside a src/images/ folder, in filename order. */
export function imagesIn(folder: string): (WebImage & { name: string })[] {
	const prefix = `${folder.replace(/\/$/, '')}/`;
	const paths = Object.keys(images).filter((p) => p.startsWith(prefix) && !p.slice(prefix.length).includes('/'));
	if (paths.length === 0) throw new Error(`No images in src/images/${folder}.`);
	return paths.sort().map((path) => ({ ...image(path), name: path.slice(prefix.length) }));
}
