title: "Kristoff Malejczuk's Website"
author: Kristoff Malejczuk
markdown: kramdown
url: "https://thestudio.uno"
baseurl: ""
plugins:
    - jekyll-sitemap
    - jekyll-seo-tag
google_analytics: G-B637RMTJB4
